server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${LOCAL_ENV_USER_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:58318/user_db}
    username: ${LOCAL_ENV_USER_DATASOURCE_USERNAME:appuser}
    password: ${LOCAL_ENV_USER_DATASOURCE_PASSWORD:Password@123}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${LOCAL_SPRING_LIQUIBASE_DEFAULT_SCHEMA:user_mgmt}
    liquibase-schema: ${LOCAL_SPRING_LIQUIBASE_LIQUIBASE_SCHEMA:public}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${LOCAL_SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:user_mgmt}
        jdbc:
          time_zone: UTC

app:
  payment-service:
    base-url: ${LOCAL_APP_PAYMENT_SERVICE_BASE_URL:http://127.0.0.1:8083}
  dev-admin:
    enabled: ${LOCAL_APP_DEV_ADMIN_ENABLED:true}

logging:
  level:
    root: INFO
    com.electrahub.user: DEBUG
